openapi: 3.0.0
paths:
  /customers:
    post:
      operationId: CustomerController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: ''
      security: []
      summary: ''
      tags:
        - Customer
  /tenant:
    post:
      operationId: TenantController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenantDto'
      responses:
        '201':
          description: The tenant has been successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTenantResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      summary: Create a new tenant
      tags:
        - Tenant
    get:
      operationId: TenantController_getMyTenants
      parameters: []
      responses:
        '200':
          description: List of tenants belonging to the authenticated user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetMyTenantsResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      summary: Get my tenants
      tags:
        - Tenant
info:
  title: Pontuaí
  description: The Pontuaí API experience :)
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    CreateCustomerRequest:
      type: object
      properties: {}
    CreateTenantDto:
      type: object
      properties:
        name:
          type: string
          description: Tenant name
          example: Sorvete amigo
        segment:
          type: string
          description: Business segment
          example: Vestuário
        cnpj:
          type: string
          description: Business   CNPJ
          example: 00.000.000/0001-00
      required:
        - name
        - segment
        - cnpj
    CreateTenantResponse:
      type: object
      properties:
        tenantId:
          type: string
          description: The ID of the created tenant
          example: 123e4567-e89b-12d3-a456-426614174000
      required:
        - tenantId
    GetMyTenantsResponse:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the tenant
          example: 6c76be07-b690-4903-93c8-395c30ddb69a
        name:
          type: string
          description: The name of the tenant
          example: Byalsoft
        segment:
          type: string
          description: The business segment of the tenant
          example: Softhouse
        CNPJ:
          type: string
          description: The CNPJ of the tenant
          example: 30.904.014/0001-09
        active:
          type: boolean
          description: Indicates whether the tenant is active
          example: true
      required:
        - id
        - name
        - segment
        - CNPJ
        - active
security:
  - bearer: []